export const technologies = {
  adafruitIo: "Adafruit IO",
  aiAgents: "AI Agents",
  aws: "AWS",
  vitest: "Vitest",
  bun: "Bun",
  chromeDevTools: "Chrome DevTools",
  convex: "Convex",
  css: "CSS",
  docker: "Docker",
  dockerCompose: "Docker Compose",
  drizzleOrm: "Drizzle ORM",
  express: "Express.js",
  fxml: "FXML",
  git: "Git",
  github: "GitHub",
  grafana: "Grafana",
  gradle: "Gradle",
  hono: "Hono.js",
  html: "HTML",
  influxDb: "InfluxDB",
  java: "Java",
  javaFx: "JavaFX",
  javascript: "JavaScript",
  microPython: "MicroPython",
  mqtt: "MQTT",
  macos: "macOS",
  next: "Next.js",
  node: "Node.js",
  npm: "npm",
  paneruWm: "PaneruWM",
  postgresql: "PostgreSQL",
  python: "Python",
  react: "React",
  reactServerComponents: "React Server Components",
  restApis: "REST APIs",
  rss: "RSS",
  rxjs: "RxJS",
  scss: "SCSS",
  sqlite: "SQLite",
  sql: "SQL",
  supabase: "Supabase",
  tailwind: "Tailwind CSS",
  t3Env: "t3-env",
  telegraf: "Telegraf",
  typescript: "TypeScript",
  vercel: "Vercel",
  vercelAiSdk: "Vercel AI SDK",
  vite: "Vite",
  visualStudioCode: "Visual Studio Code",
  zed: "Zed",
  zod: "Zod",
  jest: "Jest",
  cicd: "CI/CD",
  rag: "RAG",
};

export type Technology = (typeof technologies)[keyof typeof technologies];
